In [8]:
import pandas
import numpy as np
import json
import glob
import os
from collections import Counter

In [2]:
all_ac_files = glob.glob(rf"D:\rncloud\Rajasthan2023IVRS\ac_*\AC*.xlsx")

df1 = pandas.DataFrame()
for x in all_ac_files:
    df = pandas.read_excel(x)
    df1 = pandas.concat([df1,df])

In [11]:
df1.loc[df1['Extention Key'] == 'A','Extention Key'] = '2'
df1['acno'] = 'ac_' +  df1['CampaignName'].str.slice(-3)
df1['Extention Key'] = df1['Extention Key'].fillna(0)

In [12]:
ac_no = df1['acno'].unique()
ac_no

array(['ac_002', 'ac_013', 'ac_020', 'ac_024', 'ac_027', 'ac_032',
       'ac_033', 'ac_055', 'ac_063', 'ac_071', 'ac_072', 'ac_079',
       'ac_092', 'ac_097', 'ac_114', 'ac_136', 'ac_144', 'ac_169',
       'ac_176', 'ac_179', 'ac_183'], dtype=object)

In [28]:
df1[df1['acno'] == 'ac_183'].head(50)

,CampaignName,Caller Number,Calling Number,CallInitDate,CallAnsDate,CallEndDate,Call Type,Call Status,CallDuration,Credit Used,Extention Key,Promt Lenght,Pulse Plan,acno
0,AC183,8071370396,9782244866,31/10/2023 19:18:33,31/10/2023 19:17:26,31/10/2023 19:17:51,Trans,NOANSWER,0,0.0,0,41,30,ac_183
1,AC183,8071370396,9982247947,31/10/2023 19:18:33,31/10/2023 19:17:41,31/10/2023 19:18:14,Trans,ANSWERED,32,2.0,0.0,41,30,ac_183
2,AC183,8071370396,7734855232,31/10/2023 19:18:33,31/10/2023 19:17:26,31/10/2023 19:17:33,Trans,BUSY,0,0.0,0,41,30,ac_183
3,AC183,8071370396,9587069372,31/10/2023 19:18:33,31/10/2023 19:17:27,31/10/2023 19:17:52,Trans,NOANSWER,0,0.0,0,41,30,ac_183
4,AC183,8071370396,9772834852,31/10/2023 19:18:33,31/10/2023 19:17:43,31/10/2023 19:18:29,Trans,ANSWERED,45,2.0,0,41,30,ac_183
5,AC183,8071370396,9610143069,31/10/2023 19:18:33,31/10/2023 19:17:34,31/10/2023 19:17:40,Trans,BUSY,0,0.0,0,41,30,ac_183
6,AC183,8071370396,9461335135,31/10/2023 19:18:33,31/10/2023 19:17:47,31/10/2023 19:18:14,Trans,ANSWERED,27,1.0,1.0,41,30,ac_183
7,AC183,8071370396,8302865858,31/10/2023 19:18:33,31/10/2023 19:17:44,31/10/2023 19:18:01,Trans,ANSWERED,17,1.0,0,41,30,ac_183
8,AC183,8071370396,9783443375,31/10/2023 19:18:33,31/10/2023 19:17:45,31/10/2023 19:18:16,Trans,ANSWERED,31,2.0,2.0,41,30,ac_183
9,AC183,8071370396,9413484801,31/10/2023 19:18:33,31/10/2023 19:17:49,31/10/2023 19:17:54,Trans,ANSWERED,4,1.0,0,41,30,ac_183
10,AC183,8071370396,9672622055,31/10/2023 19:18:33,31/10/2023 19:17:41,31/10/2023 19:17:56,Trans,BUSY,0,0.0,0,41,30,ac_183
11,AC183,8071370396,9212617352,31/10/2023 19:18:33,31/10/2023 19:17:41,31/10/2023 19:17:55,Trans,BUSY,0,0.0,0,41,30,ac_183
12,AC183,8071370396,9351359775,31/10/2023 19:18:33,31/10/2023 19:17:41,31/10/2023 19:17:56,Trans,BUSY,0,0.0,0,41,30,ac_183
13,AC183,8071370396,9772054667,31/10/2023 19:18:33,31/10/2023 19:18:00,31/10/2023 19:18:15,Trans,ANSWERED,15,1.0,0,41,30,ac_183
14,AC183,8071370396,9057021067,31/10/2023 19:18:33,31/10/2023 19:17:54,31/10/2023 19:18:06,Trans,ANSWERED,12,1.0,0,41,30,ac_183
15,AC183,8071370396,9875722272,31/10/2023 19:18:33,31/10/2023 19:18:14,31/10/2023 19:18:40,Trans,ANSWERED,25,1.0,0,41,30,ac_183
16,AC183,8071370396,7690057107,31/10/2023 19:18:33,31/10/2023 19:17:50,31/10/2023 19:18:15,Trans,BUSY,0,0.0,0,41,30,ac_183
17,AC183,8071370396,9828529112,31/10/2023 19:18:33,31/10/2023 19:17:50,31/10/2023 19:17:50,Trans,BUSY,0,0.0,0,41,30,ac_183
18,AC183,8071370396,9649866945,31/10/2023 19:18:33,31/10/2023 19:17:58,31/10/2023 19:18:25,Trans,ANSWERED,26,1.0,3.0,41,30,ac_183
19,AC183,8071370396,9602796380,31/10/2023 19:18:33,31/10/2023 19:17:50,31/10/2023 19:18:14,Trans,BUSY,0,0.0,0,41,30,ac_183
20,AC183,8071370396,9828268062,31/10/2023 19:18:33,31/10/2023 19:17:58,31/10/2023 19:18:04,Trans,BUSY,0,0.0,0,41,30,ac_183
21,AC183,8071370396,9828717161,31/10/2023 19:18:33,31/10/2023 19:17:59,31/10/2023 19:18:24,Trans,NOANSWER,0,0.0,0,41,30,ac_183
22,AC183,8071370396,8000338926,31/10/2023 19:18:33,31/10/2023 19:18:19,31/10/2023 19:19:05,Trans,ANSWERED,45,2.0,0,41,30,ac_183
23,AC183,8071370396,8875661352,31/10/2023 19:18:33,31/10/2023 19:17:59,31/10/2023 19:18:05,Trans,BUSY,0,0.0,0,41,30,ac_183
24,AC183,8071370396,8107774582,31/10/2023 19:18:33,31/10/2023 19:17:59,31/10/2023 19:18:21,Trans,BUSY,0,0.0,0,41,30,ac_183
25,AC183,8071370396,9587121791,31/10/2023 19:18:33,31/10/2023 19:18:07,31/10/2023 19:18:32,Trans,NOANSWER,0,0.0,0,41,30,ac_183
26,AC183,8071370396,9610581677,31/10/2023 19:18:33,31/10/2023 19:18:07,31/10/2023 19:18:32,Trans,NOANSWER,0,0.0,0,41,30,ac_183
27,AC183,8071370396,9649568680,31/10/2023 19:18:33,31/10/2023 19:18:07,31/10/2023 19:18:32,Trans,NOANSWER,0,0.0,0,41,30,ac_183
28,AC183,8071370396,6378786922,31/10/2023 19:18:33,31/10/2023 19:18:07,31/10/2023 19:18:32,Trans,NOANSWER,0,0.0,0,41,30,ac_183
29,AC183,8071370396,8503859067,31/10/2023 19:18:33,31/10/2023 19:18:25,31/10/2023 19:18:30,Trans,ANSWERED,4,1.0,0,41,30,ac_183
30,AC183,8071370396,9166613031,31/10/2023 19:18:33,31/10/2023 19:18:16,31/10/2023 19:18:39,Trans,BUSY,0,0.0,0,41,30,ac_183
31,AC183,8071370396,9680806866,31/10/2023 19:18:33,31/10/2023 19:18:16,31/10/2023 19:18:41,Trans,BUSY,0,0.0,0,41,30,ac_183
32,AC183,8071370396,9982431316,31/10/2023 19:18:33,31/10/2023 19:18:17,31/10/2023 19:18:42,Trans,NOANSWER,0,0.0,0,41,30,ac_183
33,AC183,8071370396,8306766819,31/10/2023 19:18:33,31/10/2023 19:18:17,31/10/2023 19:18:37,Trans,BUSY,0,0.0,0,41,30,ac_183
34,AC183,8071370396,9782296322,31/10/2023 19:18:33,31/10/2023 19:18:17,31/10/2023 19:18:17,Trans,NOANSWER,0,0.0,0,41,30,ac_183
35,AC183,8071370396,9549849538,31/10/2023 19:18:33,31/10/2023 19:18:28,31/10/2023 19:18:41,Trans,BUSY,0,0.0,0,41,30,ac_183
36,AC183,8071370396,9610350796,31/10/2023 19:18:33,31/10/2023 19:18:28,31/10/2023 19:18:52,Trans,BUSY,0,0.0,0,41,30,ac_183
37,AC183,8071370396,9782323811,31/10/2023 19:18:33,31/10/2023 19:18:28,31/10/2023 19:18:53,Trans,NOANSWER,0,0.0,0,41,30,ac_183
38,AC183,8071370396,9145899420,31/10/2023 19:18:33,31/10/2023 19:18:37,31/10/2023 19:18:42,Trans,ANSWERED,4,1.0,0,41,30,ac_183
39,AC183,8071370396,9214887607,31/10/2023 19:18:33,31/10/2023 19:18:28,31/10/2023 19:18:42,Trans,BUSY,0,0.0,0,41,30,ac_183
40,AC183,8071370396,9983564919,31/10/2023 19:18:33,31/10/2023 19:18:38,31/10/2023 19:18:38,Trans,NOANSWER,0,0.0,0,41,30,ac_183
41,AC183,8071370396,8107794161,31/10/2023 19:18:33,31/10/2023 19:18:38,31/10/2023 19:18:53,Trans,BUSY,0,0.0,0,41,30,ac_183
42,AC183,8071370396,9929763450,31/10/2023 19:18:33,31/10/2023 19:18:38,31/10/2023 19:19:03,Trans,NOANSWER,0,0.0,0,41,30,ac_183
43,AC183,8071370396,8003637252,31/10/2023 19:18:33,31/10/2023 19:18:54,31/10/2023 19:19:00,Trans,ANSWERED,6,1.0,0,41,30,ac_183
44,AC183,8071370396,8075788100,31/10/2023 19:18:33,31/10/2023 19:18:38,31/10/2023 19:19:03,Trans,NOANSWER,0,0.0,0,41,30,ac_183
45,AC183,8071370396,9898582982,31/10/2023 19:18:33,31/10/2023 19:18:58,31/10/2023 19:19:03,Trans,ANSWERED,5,1.0,0,41,30,ac_183
46,AC183,8071370396,9549028886,31/10/2023 19:18:33,31/10/2023 19:18:51,31/10/2023 19:19:16,Trans,NOANSWER,0,0.0,0,41,30,ac_183
47,AC183,8071370396,9462406090,31/10/2023 19:18:33,31/10/2023 19:19:09,31/10/2023 19:19:55,Trans,ANSWERED,45,2.0,0,41,30,ac_183
48,AC183,8071370396,9799516418,31/10/2023 19:18:33,31/10/2023 19:19:01,31/10/2023 19:19:09,Trans,ANSWERED,7,1.0,0,41,30,ac_183
49,AC183,8071370396,9983919142,31/10/2023 19:18:33,31/10/2023 19:18:51,31/10/2023 19:18:59,Trans,BUSY,0,0.0,0,41,30,ac_183

In [163]:
def candsupport(ac, json_pathname):
    
    extensions = [str(int(x)) for x in ac['Extention Key'] if x not in ('*', '#', '0','D','B', np.nan)]
    extension_counts = dict(Counter(extensions))
    sorted(extension_counts.items(), key=lambda x : x[1], reverse = True)

    choice_path = json_pathname

    with open(choice_path) as json_file:
        choice = json.load(json_file)



    choice_key = {}
    for key, value in extension_counts.items():
        if key == '9':
            key = 'Others'
            choice_key[key] = int(value)
        elif key in choice.keys():
            for key1, value1 in choice.items():
                if key == key1:
                    key = value1
                    choice_key[key] = int(value)
        else:
            continue

    choice_key = dict(sorted(choice_key.items(), key = lambda x : x[1], reverse = True))
    


    total = sum(choice_key.values())

    support = {}
    #support['name'] = ['% vote','vote']
    for i,j in choice_key.items():
        support[i] = {round((j/total) * 100, 2),j}
    #support['Total'] = ['100%',total]    
    
    return support

In [164]:
ac_no_name = []
for i, row in ac_name.iterrows():
    for x in ac_no:
        if row['AC No'] == x:
            ac_no_name.append([x,row['AC Name']])
            
ac_support = {}
for index,name in enumerate(ac_no):
    df3 = df1[df1['acno'] == name]
    path = "D:\\rncloud\\Rajasthan2023IVRS\\"+name+"\\choices.json"
    print(path)
    json_pathname = glob.glob(path)
    #for j in json_pathname:
    result = candsupport(df3,json_pathname[0])
    num_name = ''
    for x in ac_no_name[index]:
        num_name += x + " "
    #print(num_name)
        
    ac_support[num_name[:(len(num_name)-1)]] = result

D:\rncloud\Rajasthan2023IVRS\ac_002\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_013\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_020\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_024\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_027\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_032\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_033\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_055\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_063\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_071\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_072\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_079\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_092\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_097\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_114\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_136\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_144\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_169\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_176\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_179\choices.json
D:\rncloud\Rajasthan2023IVRS\ac_183\choices.json

In [170]:
ac_support

{'ac_002 Ganganagar': {'Jaydeep Bihani (BJP)': {38.96, 526},
  'ASHOK CHANDAK (Congress)': {29.93, 404},
  'RAJ KUMAR GAUR (IND)': {12.59, 170},
  'Others': {10.67, 144},
  'Dr. Harish Raheja (AAP)': {4.15, 56},
  'Vinita Ahuja (IND)': {3.7, 50}},
 'ac_013 Bikaner West': {'Jethanand Vyas (BJP)': {49.12, 392},
  'BULAKI DAS KALLA (Congress)': {35.59, 284},
  'Mahaveer Raka (IND)': {6.77, 54},
  'Others': {4.76, 38},
  'Manish Sharma (AAP)': {2.01, 16},
  'Gokul Joshi (IND)': {1.75, 14}},
 'ac_020 Taranagar': {'Rajendra Rathore (BJP)': {46.46, 446},
  'NARENDRA BUDANIYA (Congress)': {43.12, 414},
  'Others': {6.04, 58},
  'RAKESH JANGID (IND)': {3.12, 30},
  'Chhoturam (BSP)': {1.25, 12}},
 'ac_024 Sujangarh (Sc)': {'MANOJ MEGHWAL (Congress)': {42.41, 564},
  'SANTOSH MEGHWAL (BJP)': {35.34, 470},
  'Others': {15.04, 200},
  'BL Bhati (IND)': {7.22, 96}},
 'ac_027 Jhunjhunu': {'BRIJENDRA SINGH OLA (Congress)': {38.45, 606},
  'Nischit aka Bablu Chaudhary (BJP)': {30.2, 476},
  'RAJENDRA SINGH BHAMBOO (IND)': {20.69, 326},
  'Others': {10.66, 168}},
 'ac_032 Fatehpur': {'HAKAM ALI KHAN (Congress)': {7, 31.82},
  'Shravan Chaudhary (BJP)': {6, 27.27},
  'Nand Kishore Mahariya (JJP)': {5, 22.73},
  'Others': {3, 13.64},
  'Javed Ali Khan (AIMIM)': {1, 4.55}},
 'ac_033 Lachmangarh': {},
 'ac_055 Sanganer': {'Pushpendra Bharadwaj (Congress)': {50.75, 68},
  'Bhajanlal Sharma (BJP)': {43.28, 58},
  'Mahesh Saini (RLP)': {2.99, 4},
  'Others': {2.99, 4}},
 'ac_063 Bansur': {'SHAKUNTALA RAWAT (Congress)': {28, 36.84},
  'DEVI SINGH SHEKHAWAT (BJP)': {26, 34.21},
  'Others': {10, 13.16},
  'Mahendra Yadav (IND)': {6, 7.89},
  'Mukesh Yadav (BSP)': {4, 5.26},
  'Dr. Rohitash Sharma (IND)': {2, 2.63}},
 'ac_071 Nagar': {'Jawahar Singh Bedam (BJP)': {38.16, 638},
  'WAJIB ALI (Congress)': {34.21, 572},
  'Nem Singh (IND)': {17.22, 288},
  'Others': {5.14, 86},
  'Anita Singh Gurjar (IND)': {2.75, 46},
  'Khurshid Ahmad (BSP)': {2.51, 42}},
 'ac_072 Deeg Kumher': {'DR. SHAILESH SINGH (BJP)': {45.7, 690},
  'VISHVENDRA SINGH (Congress)': {41.72, 630},
  'Others': {7.95, 120},
  'Hariom Sharma (BSP)': {4.64, 70}},
 'ac_079 Dholpur': {'DR. SHIV CHARAN SINGH KUSHAWAH (BJP)': {33.17, 418},
  'SHOBHARANI KUSHWAH (Congress)': {30.0, 378},
  'Ritesh Sharma (BSP)': {27.14, 342},
  'Others': {9.68, 122}},
 'ac_092 Sawai Madhopur': {'DR. KIRORI LAL MEENA (BJP)': {38.0, 614},
  'DANISH ABRAR (Congress)': {25.62, 414},
  'ASHA MEENA (IND)': {22.77, 368},
  'Others': {8.54, 138},
  'Mukesh Bhupremi (AAP)': {3.22, 52},
  'Brahmsingh Gurjar (BSP)': {1.86, 30}},
 'ac_097 Deoli - Uniara': {'VIJAY BAINSLA (BJP)': {38.07, 134},
  'HARISH CHANDRA MEENA M (Congress)': {35.23, 124},
  'Others': {13.07, 46},
  'PRABHU LAL SAINI (IND)': {5.68, 20},
  'RAJENDRA GURJAR (IND)': {4.55, 16},
  'Dr. Rajendra Singh Meena (AAP)': {3.41, 12}},
 'ac_114 Parbatsar': {'RAMNIWAS GAWRIYA (Congress)': {42.06, 45},
  'MAN SINGH KINSARIYA (BJP)': {28.04, 30},
  'LACHCHARAM BADARHA (RLP)': {22.43, 24},
  'Others': {7.48, 8}},
 'ac_136 Baytoo': {'HARISH CHOUDHARY (Congress)': {37.42, 598},
  'Balram Mund (BJP)': {28.91, 462},
  'UMMEDA RAM (RLTP)': {26.28, 420},
  'Others': {7.38, 118}},
 'ac_144 Sanchore': {'SUKHRAM VISHNOI (Congress)': {36.19, 786},
  'JEEVA RAM CHOUDHARY (BJP)': {31.49, 684},
  'DANA RAM CHOUDHARY (BJP)': {13.17, 286},
  'DEVJI PATEL (BJP)': {11.05, 240},
  'Others': {6.54, 142},
  'Ram Lal Vishnoi (AAP)': {1.57, 34}},
 'ac_169 Chittorgarh': {'CHANDRABHAN SINGH AAKYA (IND)': {59.37, 1248},
  'SURENDRA SINGH JADAWAT (Congress)': {23.03, 484},
  'NARPAT SINGH RAJVI (BJP)': {13.42, 282},
  'Others': {4.19, 88}},
 'ac_176 Nathdwara': {'C. P. JOSHI (Congress)': {47.85, 356},
  'Kunwar Vishwaraj Singh Mewar  (BJP)': {43.82, 326},
  'Others': {6.45, 48},
  'Babulal Salvi (BSP)': {1.88, 14}},
 'ac_179 Sahara': {'Ladulal Pitalia (BJP)': {58.46, 898},
  'Rajendra Trivedi (Congress)': {25.91, 398},
  'Badrilal Jat (RLP)': {10.42, 160},
  'Others': {5.21, 80}},
 'ac_183 Mandalgarh': {'VIVEK DHAKAR (Congress)': {41.07, 46},
  'GOPAL LAL SHARMA (BJP)': {33.93, 38},
  'SHAKTI SINGH HADA (IND)': {16.07, 18},
  'Others': {8.93, 10}}}

In [171]:
for row, (key,value) in enumerate(ac_support)

{'ac_002 Ganganagar': {'Jaydeep Bihani (BJP)': {38.96, 526},
  'ASHOK CHANDAK (Congress)': {29.93, 404},
  'RAJ KUMAR GAUR (IND)': {12.59, 170},
  'Others': {10.67, 144},
  'Dr. Harish Raheja (AAP)': {4.15, 56},
  'Vinita Ahuja (IND)': {3.7, 50}},
 'ac_013 Bikaner West': {'Jethanand Vyas (BJP)': {49.12, 392},
  'BULAKI DAS KALLA (Congress)': {35.59, 284},
  'Mahaveer Raka (IND)': {6.77, 54},
  'Others': {4.76, 38},
  'Manish Sharma (AAP)': {2.01, 16},
  'Gokul Joshi (IND)': {1.75, 14}},
 'ac_020 Taranagar': {'Rajendra Rathore (BJP)': {46.46, 446},
  'NARENDRA BUDANIYA (Congress)': {43.12, 414},
  'Others': {6.04, 58},
  'RAKESH JANGID (IND)': {3.12, 30},
  'Chhoturam (BSP)': {1.25, 12}},
 'ac_024 Sujangarh (Sc)': {'MANOJ MEGHWAL (Congress)': {42.41, 564},
  'SANTOSH MEGHWAL (BJP)': {35.34, 470},
  'Others': {15.04, 200},
  'BL Bhati (IND)': {7.22, 96}},
 'ac_027 Jhunjhunu': {'BRIJENDRA SINGH OLA (Congress)': {38.45, 606},
  'Nischit aka Bablu Chaudhary (BJP)': {30.2, 476},
  'RAJENDRA SINGH BHAMBOO (IND)': {20.69, 326},
  'Others': {10.66, 168}},
 'ac_032 Fatehpur': {'HAKAM ALI KHAN (Congress)': {7, 31.82},
  'Shravan Chaudhary (BJP)': {6, 27.27},
  'Nand Kishore Mahariya (JJP)': {5, 22.73},
  'Others': {3, 13.64},
  'Javed Ali Khan (AIMIM)': {1, 4.55}},
 'ac_033 Lachmangarh': {},
 'ac_055 Sanganer': {'Pushpendra Bharadwaj (Congress)': {50.75, 68},
  'Bhajanlal Sharma (BJP)': {43.28, 58},
  'Mahesh Saini (RLP)': {2.99, 4},
  'Others': {2.99, 4}},
 'ac_063 Bansur': {'SHAKUNTALA RAWAT (Congress)': {28, 36.84},
  'DEVI SINGH SHEKHAWAT (BJP)': {26, 34.21},
  'Others': {10, 13.16},
  'Mahendra Yadav (IND)': {6, 7.89},
  'Mukesh Yadav (BSP)': {4, 5.26},
  'Dr. Rohitash Sharma (IND)': {2, 2.63}},
 'ac_071 Nagar': {'Jawahar Singh Bedam (BJP)': {38.16, 638},
  'WAJIB ALI (Congress)': {34.21, 572},
  'Nem Singh (IND)': {17.22, 288},
  'Others': {5.14, 86},
  'Anita Singh Gurjar (IND)': {2.75, 46},
  'Khurshid Ahmad (BSP)': {2.51, 42}},
 'ac_072 Deeg Kumher': {'DR. SHAILESH SINGH (BJP)': {45.7, 690},
  'VISHVENDRA SINGH (Congress)': {41.72, 630},
  'Others': {7.95, 120},
  'Hariom Sharma (BSP)': {4.64, 70}},
 'ac_079 Dholpur': {'DR. SHIV CHARAN SINGH KUSHAWAH (BJP)': {33.17, 418},
  'SHOBHARANI KUSHWAH (Congress)': {30.0, 378},
  'Ritesh Sharma (BSP)': {27.14, 342},
  'Others': {9.68, 122}},
 'ac_092 Sawai Madhopur': {'DR. KIRORI LAL MEENA (BJP)': {38.0, 614},
  'DANISH ABRAR (Congress)': {25.62, 414},
  'ASHA MEENA (IND)': {22.77, 368},
  'Others': {8.54, 138},
  'Mukesh Bhupremi (AAP)': {3.22, 52},
  'Brahmsingh Gurjar (BSP)': {1.86, 30}},
 'ac_097 Deoli - Uniara': {'VIJAY BAINSLA (BJP)': {38.07, 134},
  'HARISH CHANDRA MEENA M (Congress)': {35.23, 124},
  'Others': {13.07, 46},
  'PRABHU LAL SAINI (IND)': {5.68, 20},
  'RAJENDRA GURJAR (IND)': {4.55, 16},
  'Dr. Rajendra Singh Meena (AAP)': {3.41, 12}},
 'ac_114 Parbatsar': {'RAMNIWAS GAWRIYA (Congress)': {42.06, 45},
  'MAN SINGH KINSARIYA (BJP)': {28.04, 30},
  'LACHCHARAM BADARHA (RLP)': {22.43, 24},
  'Others': {7.48, 8}},
 'ac_136 Baytoo': {'HARISH CHOUDHARY (Congress)': {37.42, 598},
  'Balram Mund (BJP)': {28.91, 462},
  'UMMEDA RAM (RLTP)': {26.28, 420},
  'Others': {7.38, 118}},
 'ac_144 Sanchore': {'SUKHRAM VISHNOI (Congress)': {36.19, 786},
  'JEEVA RAM CHOUDHARY (BJP)': {31.49, 684},
  'DANA RAM CHOUDHARY (BJP)': {13.17, 286},
  'DEVJI PATEL (BJP)': {11.05, 240},
  'Others': {6.54, 142},
  'Ram Lal Vishnoi (AAP)': {1.57, 34}},
 'ac_169 Chittorgarh': {'CHANDRABHAN SINGH AAKYA (IND)': {59.37, 1248},
  'SURENDRA SINGH JADAWAT (Congress)': {23.03, 484},
  'NARPAT SINGH RAJVI (BJP)': {13.42, 282},
  'Others': {4.19, 88}},
 'ac_176 Nathdwara': {'C. P. JOSHI (Congress)': {47.85, 356},
  'Kunwar Vishwaraj Singh Mewar  (BJP)': {43.82, 326},
  'Others': {6.45, 48},
  'Babulal Salvi (BSP)': {1.88, 14}},
 'ac_179 Sahara': {'Ladulal Pitalia (BJP)': {58.46, 898},
  'Rajendra Trivedi (Congress)': {25.91, 398},
  'Badrilal Jat (RLP)': {10.42, 160},
  'Others': {5.21, 80}},
 'ac_183 Mandalgarh': {'VIVEK DHAKAR (Congress)': {41.07, 46},
  'GOPAL LAL SHARMA (BJP)': {33.93, 38},
  'SHAKTI SINGH HADA (IND)': {16.07, 18},
  'Others': {8.93, 10}}}

In [135]:
file_path = 'supportivrsfinal.json'
with open(file_path,'w') as file_name:
    json.dump(ac_support,file_name,indent=4)

In [150]:
pdf = pandas.DataFrame(ac_support.items())

In [159]:
for i, j in pdf.items():
    for n,m in j.items():
        print(n,m)

0 ac_002 Ganganagar
1 ac_013 Bikaner West
2 ac_020 Taranagar
3 ac_024 Sujangarh (Sc)
4 ac_027 Jhunjhunu
5 ac_032 Fatehpur
6 ac_033 Lachmangarh
7 ac_055 Sanganer
8 ac_063 Bansur
9 ac_071 Nagar
10 ac_072 Deeg Kumher
11 ac_079 Dholpur
12 ac_092 Sawai Madhopur
13 ac_097 Deoli - Uniara
14 ac_114 Parbatsar
15 ac_136 Baytoo
16 ac_144 Sanchore
17 ac_169 Chittorgarh
18 ac_176 Nathdwara
19 ac_179 Sahara
20 ac_183 Mandalgarh
0 {'name': ['% vote', 'vote'], 'Jaydeep Bihani (BJP)': [38.96, 526], 'ASHOK CHANDAK (Congress)': [29.93, 404], 'RAJ KUMAR GAUR (IND)': [12.59, 170], 'Others': [10.67, 144], 'Dr. Harish Raheja (AAP)': [4.15, 56], 'Vinita Ahuja (IND)': [3.7, 50], 'Total': ['100%', 1350]}
1 {'name': ['% vote', 'vote'], 'Jethanand Vyas (BJP)': [49.12, 392], 'BULAKI DAS KALLA (Congress)': [35.59, 284], 'Mahaveer Raka (IND)': [6.77, 54], 'Others': [4.76, 38], 'Manish Sharma (AAP)': [2.01, 16], 'Gokul Joshi (IND)': [1.75, 14], 'Total': ['100%', 798]}
2 {'name': ['% vote', 'vote'], 'Rajendra Rathore (BJP)': [46.46, 446], 'NARENDRA BUDANIYA (Congress)': [43.12, 414], 'Others': [6.04, 58], 'RAKESH JANGID (IND)': [3.12, 30], 'Chhoturam (BSP)': [1.25, 12], 'Total': ['100%', 960]}
3 {'name': ['% vote', 'vote'], 'MANOJ MEGHWAL (Congress)': [42.41, 564], 'SANTOSH MEGHWAL (BJP)': [35.34, 470], 'Others': [15.04, 200], 'BL Bhati (IND)': [7.22, 96], 'Total': ['100%', 1330]}
4 {'name': ['% vote', 'vote'], 'BRIJENDRA SINGH OLA (Congress)': [38.45, 606], 'Nischit aka Bablu Chaudhary (BJP)': [30.2, 476], 'RAJENDRA SINGH BHAMBOO (IND)': [20.69, 326], 'Others': [10.66, 168], 'Total': ['100%', 1576]}
5 {'name': ['% vote', 'vote'], 'HAKAM ALI KHAN (Congress)': [31.82, 7], 'Shravan Chaudhary (BJP)': [27.27, 6], 'Nand Kishore Mahariya (JJP)': [22.73, 5], 'Others': [13.64, 3], 'Javed Ali Khan (AIMIM)': [4.55, 1], 'Total': ['100%', 22]}
6 {'name': ['% vote', 'vote'], 'Total': ['100%', 0]}
7 {'name': ['% vote', 'vote'], 'Pushpendra Bharadwaj (Congress)': [50.75, 68], 'Bhajanlal Sharma (BJP)': [43.28, 58], 'Mahesh Saini (RLP)': [2.99, 4], 'Others': [2.99, 4], 'Total': ['100%', 134]}
8 {'name': ['% vote', 'vote'], 'SHAKUNTALA RAWAT (Congress)': [36.84, 28], 'DEVI SINGH SHEKHAWAT (BJP)': [34.21, 26], 'Others': [13.16, 10], 'Mahendra Yadav (IND)': [7.89, 6], 'Mukesh Yadav (BSP)': [5.26, 4], 'Dr. Rohitash Sharma (IND)': [2.63, 2], 'Total': ['100%', 76]}
9 {'name': ['% vote', 'vote'], 'Jawahar Singh Bedam (BJP)': [38.16, 638], 'WAJIB ALI (Congress)': [34.21, 572], 'Nem Singh (IND)': [17.22, 288], 'Others': [5.14, 86], 'Anita Singh Gurjar (IND)': [2.75, 46], 'Khurshid Ahmad (BSP)': [2.51, 42], 'Total': ['100%', 1672]}
10 {'name': ['% vote', 'vote'], 'DR. SHAILESH SINGH (BJP)': [45.7, 690], 'VISHVENDRA SINGH (Congress)': [41.72, 630], 'Others': [7.95, 120], 'Hariom Sharma (BSP)': [4.64, 70], 'Total': ['100%', 1510]}
11 {'name': ['% vote', 'vote'], 'DR. SHIV CHARAN SINGH KUSHAWAH (BJP)': [33.17, 418], 'SHOBHARANI KUSHWAH (Congress)': [30.0, 378], 'Ritesh Sharma (BSP)': [27.14, 342], 'Others': [9.68, 122], 'Total': ['100%', 1260]}
12 {'name': ['% vote', 'vote'], 'DR. KIRORI LAL MEENA (BJP)': [38.0, 614], 'DANISH ABRAR (Congress)': [25.62, 414], 'ASHA MEENA (IND)': [22.77, 368], 'Others': [8.54, 138], 'Mukesh Bhupremi (AAP)': [3.22, 52], 'Brahmsingh Gurjar (BSP)': [1.86, 30], 'Total': ['100%', 1616]}
13 {'name': ['% vote', 'vote'], 'VIJAY BAINSLA (BJP)': [38.07, 134], 'HARISH CHANDRA MEENA M (Congress)': [35.23, 124], 'Others': [13.07, 46], 'PRABHU LAL SAINI (IND)': [5.68, 20], 'RAJENDRA GURJAR (IND)': [4.55, 16], 'Dr. Rajendra Singh Meena (AAP)': [3.41, 12], 'Total': ['100%', 352]}
14 {'name': ['% vote', 'vote'], 'RAMNIWAS GAWRIYA (Congress)': [42.06, 45], 'MAN SINGH KINSARIYA (BJP)': [28.04, 30], 'LACHCHARAM BADARHA (RLP)': [22.43, 24], 'Others': [7.48, 8], 'Total': ['100%', 107]}
15 {'name': ['% vote', 'vote'], 'HARISH CHOUDHARY (Congress)': [37.42, 598], 'Balram Mund (BJP)': [28.91, 462], 'UMMEDA RAM (RLTP)': [26.28, 420], 'Others': [7.38, 118], 'Total': ['100%', 1598]}
16 {'name': ['% vote', 'vote'], 'SUKHRAM VISHNOI (Congress)': [36.19, 786], 'JEEVA RAM CHOUDHARY (BJP)': [31.49, 684], 'DANA RAM CHOUDHARY (BJP)': [13.17, 286], 'DEVJI PATEL (BJP)': [11.05, 240], 'Others': [6.54, 142], 'Ram Lal Vishnoi (AAP)': [1.57, 34], 'Total': ['100%', 2172]}
17 {'name': ['% vote', 'vote'], 'CHANDRABHAN SINGH AAKYA (IND)': [59.37, 1248], 'SURENDRA SINGH JADAWAT (Congress)': [23.03, 484], 'NARPAT SINGH RAJVI (BJP)': [13.42, 282], 'Others': [4.19, 88], 'Total': ['100%', 2102]}
18 {'name': ['% vote', 'vote'], 'C. P. JOSHI (Congress)': [47.85, 356], 'Kunwar Vishwaraj Singh Mewar  (BJP)': [43.82, 326], 'Others': [6.45, 48], 'Babulal Salvi (BSP)': [1.88, 14], 'Total': ['100%', 744]}
19 {'name': ['% vote', 'vote'], 'Ladulal Pitalia (BJP)': [58.46, 898], 'Rajendra Trivedi (Congress)': [25.91, 398], 'Badrilal Jat (RLP)': [10.42, 160], 'Others': [5.21, 80], 'Total': ['100%', 1536]}
20 {'name': ['% vote', 'vote'], 'VIVEK DHAKAR (Congress)': [41.07, 46], 'GOPAL LAL SHARMA (BJP)': [33.93, 38], 'SHAKTI SINGH HADA (IND)': [16.07, 18], 'Others': [8.93, 10], 'Total': ['100%', 112]}

In [67]:
ac_name = pandas.read_excel(fr"D:\rajasthan\AC no and names.xlsx")
ac_name['AC No'] = ac_name['AC No'].astype(str)
ac_name['AC No'] = 'ac_' + ac_name['AC No'].str.zfill(3)
ac_name

      AC No             AC Name
0    ac_001         Sadulshahar
1    ac_002          Ganganagar
2    ac_003            Karanpur
3    ac_004           Suratgarh
4    ac_005  Raisinghnagar (Sc)
..      ...                 ...
195  ac_196             Chhabra
196  ac_197            Dag (Sc)
197  ac_198         Jhalrapatan
198  ac_199             Khanpur
199  ac_200       Manohar Thana

[200 rows x 2 columns]

In [102]:
ac_no_name = []
for i, row in ac_name.iterrows():
    for x in ac_no:
        if row['AC No'] == x:
            ac_no_name.append((x,row['AC Name']))

"('ac_002', 'Ganganagar')"